// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "LDrawPlayground",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "LDrawPlayground",
            targets: ["LDrawPlayground"],
            bundleIdentifier: "com.millertech.ldraw-playground",
            teamIdentifier: "4W79SG34MW",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .star),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .phone,
                .pad
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeLeft,
                .landscapeRight
            ]
        )
    ],
    dependencies: [
        .package(path: "../..")
    ],
    targets: [
        .executableTarget(
            name: "LDrawPlayground",
            dependencies: [
                .product(name: "LegoDrawFile", package: "swift-lego-draw"),
                .product(name: "LDrawGLES", package: "swift-lego-draw")
            ],
            resources: [
                .copy("ldraw")
            ]
        )
    ]
)